server:
  port: 8081

logging:
  file:
    max-size: 100MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) %level %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) %level %clr(%logger :) %message%n"

  level:
    root: INFO
    org.springframework.web: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      fail-fast: true

    stream:
      defaut:
        contentType: application/json
      binders:
        number_counter_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.100.9.189
                port: 5672
                username: guest
                password: guest
                virtual-host: /

      bindigs:
        number_message:
          binder: number_counter_binder
          destination: number_message
          content-type: application/json